<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="5" ignored="0" total="7" passed="2">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="101151" started-at="2020-10-25T13:16:39 IST" finished-at="2020-10-25T13:18:20 IST">
    <groups>
    </groups>
    <test name="Default test" duration-ms="101151" started-at="2020-10-25T13:16:39 IST" finished-at="2020-10-25T13:18:20 IST">
      <class name="com.weather.tests.WeatherTest">
        <test-method status="PASS" signature="InitializeBrowser()[pri:0, instance:com.weather.tests.WeatherTest@32d2fa64]" name="InitializeBrowser" is-config="true" duration-ms="10311" started-at="2020-10-25T13:16:39 IST" finished-at="2020-10-25T13:16:50 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- InitializeBrowser -->
        <test-method status="FAIL" signature="getWeather(java.lang.String)[pri:0, instance:com.weather.tests.WeatherTest@32d2fa64]" name="getWeather" duration-ms="8200" started-at="2020-10-25T13:16:50 IST" data-provider="getCity" finished-at="2020-10-25T13:16:58 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[Delhi]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:819)
at org.testng.Assert.assertEquals(Assert.java:829)
at com.weather.tests.WeatherTest.getWeather(WeatherTest.java:100)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getWeather -->
        <test-method status="PASS" signature="TearDown()[pri:0, instance:com.weather.tests.WeatherTest@32d2fa64]" name="TearDown" is-config="true" duration-ms="675" started-at="2020-10-25T13:16:58 IST" finished-at="2020-10-25T13:16:58 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TearDown -->
        <test-method status="PASS" signature="InitializeBrowser()[pri:0, instance:com.weather.tests.WeatherTest@32d2fa64]" name="InitializeBrowser" is-config="true" duration-ms="8572" started-at="2020-10-25T13:16:58 IST" finished-at="2020-10-25T13:17:07 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- InitializeBrowser -->
        <test-method status="PASS" signature="getWeather(java.lang.String)[pri:0, instance:com.weather.tests.WeatherTest@32d2fa64]" name="getWeather" duration-ms="5708" started-at="2020-10-25T13:17:07 IST" data-provider="getCity" finished-at="2020-10-25T13:17:13 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[Chandigarh]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getWeather -->
        <test-method status="PASS" signature="TearDown()[pri:0, instance:com.weather.tests.WeatherTest@32d2fa64]" name="TearDown" is-config="true" duration-ms="667" started-at="2020-10-25T13:17:13 IST" finished-at="2020-10-25T13:17:13 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TearDown -->
        <test-method status="PASS" signature="InitializeBrowser()[pri:0, instance:com.weather.tests.WeatherTest@32d2fa64]" name="InitializeBrowser" is-config="true" duration-ms="8100" started-at="2020-10-25T13:17:13 IST" finished-at="2020-10-25T13:17:21 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- InitializeBrowser -->
        <test-method status="FAIL" signature="getWeather(java.lang.String)[pri:0, instance:com.weather.tests.WeatherTest@32d2fa64]" name="getWeather" duration-ms="4808" started-at="2020-10-25T13:17:21 IST" data-provider="getCity" finished-at="2020-10-25T13:17:26 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[Indore]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:819)
at org.testng.Assert.assertEquals(Assert.java:829)
at com.weather.tests.WeatherTest.getWeather(WeatherTest.java:100)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getWeather -->
        <test-method status="PASS" signature="TearDown()[pri:0, instance:com.weather.tests.WeatherTest@32d2fa64]" name="TearDown" is-config="true" duration-ms="650" started-at="2020-10-25T13:17:26 IST" finished-at="2020-10-25T13:17:27 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TearDown -->
        <test-method status="PASS" signature="InitializeBrowser()[pri:0, instance:com.weather.tests.WeatherTest@32d2fa64]" name="InitializeBrowser" is-config="true" duration-ms="8389" started-at="2020-10-25T13:17:27 IST" finished-at="2020-10-25T13:17:35 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- InitializeBrowser -->
        <test-method status="PASS" signature="getWeather(java.lang.String)[pri:0, instance:com.weather.tests.WeatherTest@32d2fa64]" name="getWeather" duration-ms="5721" started-at="2020-10-25T13:17:35 IST" data-provider="getCity" finished-at="2020-10-25T13:17:41 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[Mumbai]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getWeather -->
        <test-method status="PASS" signature="TearDown()[pri:0, instance:com.weather.tests.WeatherTest@32d2fa64]" name="TearDown" is-config="true" duration-ms="655" started-at="2020-10-25T13:17:41 IST" finished-at="2020-10-25T13:17:42 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TearDown -->
        <test-method status="PASS" signature="InitializeBrowser()[pri:0, instance:com.weather.tests.WeatherTest@32d2fa64]" name="InitializeBrowser" is-config="true" duration-ms="7701" started-at="2020-10-25T13:17:42 IST" finished-at="2020-10-25T13:17:49 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- InitializeBrowser -->
        <test-method status="FAIL" signature="getWeather(java.lang.String)[pri:0, instance:com.weather.tests.WeatherTest@32d2fa64]" name="getWeather" duration-ms="4407" started-at="2020-10-25T13:17:49 IST" data-provider="getCity" finished-at="2020-10-25T13:17:54 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[Kolkata]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:819)
at org.testng.Assert.assertEquals(Assert.java:829)
at com.weather.tests.WeatherTest.getWeather(WeatherTest.java:100)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getWeather -->
        <test-method status="PASS" signature="TearDown()[pri:0, instance:com.weather.tests.WeatherTest@32d2fa64]" name="TearDown" is-config="true" duration-ms="685" started-at="2020-10-25T13:17:54 IST" finished-at="2020-10-25T13:17:54 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TearDown -->
        <test-method status="PASS" signature="InitializeBrowser()[pri:0, instance:com.weather.tests.WeatherTest@32d2fa64]" name="InitializeBrowser" is-config="true" duration-ms="10713" started-at="2020-10-25T13:17:54 IST" finished-at="2020-10-25T13:18:05 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- InitializeBrowser -->
        <test-method status="FAIL" signature="getWeather(java.lang.String)[pri:0, instance:com.weather.tests.WeatherTest@32d2fa64]" name="getWeather" duration-ms="1388" started-at="2020-10-25T13:18:05 IST" data-provider="getCity" finished-at="2020-10-25T13:18:07 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[Newyork]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.RuntimeException">
            <message>
              <![CDATA[HttpResponseCode404]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.RuntimeException: HttpResponseCode404
at com.weather.Utilities.DoGetWeatherRequest.doGetRequest(DoGetWeatherRequest.java:31)
at com.weather.Utilities.DoGetWeatherRequest.getTemperature(DoGetWeatherRequest.java:45)
at com.weather.tests.WeatherTest.getWeather(WeatherTest.java:64)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.RuntimeException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getWeather -->
        <test-method status="PASS" signature="TearDown()[pri:0, instance:com.weather.tests.WeatherTest@32d2fa64]" name="TearDown" is-config="true" duration-ms="653" started-at="2020-10-25T13:18:07 IST" finished-at="2020-10-25T13:18:07 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TearDown -->
        <test-method status="PASS" signature="InitializeBrowser()[pri:0, instance:com.weather.tests.WeatherTest@32d2fa64]" name="InitializeBrowser" is-config="true" duration-ms="7164" started-at="2020-10-25T13:18:07 IST" finished-at="2020-10-25T13:18:14 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- InitializeBrowser -->
        <test-method status="FAIL" signature="getWeather(java.lang.String)[pri:0, instance:com.weather.tests.WeatherTest@32d2fa64]" name="getWeather" duration-ms="5233" started-at="2020-10-25T13:18:14 IST" data-provider="getCity" finished-at="2020-10-25T13:18:20 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[Texas]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:819)
at org.testng.Assert.assertEquals(Assert.java:829)
at com.weather.tests.WeatherTest.getWeather(WeatherTest.java:100)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getWeather -->
        <test-method status="PASS" signature="TearDown()[pri:0, instance:com.weather.tests.WeatherTest@32d2fa64]" name="TearDown" is-config="true" duration-ms="679" started-at="2020-10-25T13:18:20 IST" finished-at="2020-10-25T13:18:20 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TearDown -->
      </class> <!-- com.weather.tests.WeatherTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
